# Generated by Django 5.2.7 on 2025-10-30 17:31

import comments.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=comments.utils.get_file_upload_path),
        ),
    ]
